#
# Copyright (C) 2022 Dalton Martins <daltonvlm@gmail.com>
#
# This file is part of Virtual SNMP Agent.
#
# Virtual SNMP Agent is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Virtual SNMP Agent is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Virtual SNMP Agent.  If not, see <http://www.gnu.org/licenses/>.
#

FROM ubuntu
MAINTAINER Dalton Martins

RUN apt update && apt upgrade -y
RUN apt install libsnmp-dev -y
RUN apt install libsnmp-perl -y
RUN apt install autoconf -y
RUN apt install build-essential -y
RUN apt install pkg-config -y
RUN apt install libglib2.0-dev -y

WORKDIR /root
COPY . .
RUN ./autogen.sh
RUN make install
RUN mkdir .snmp

ENTRYPOINT ["vsa"]
